import './globals.css';
import type { Metadata } from 'next';
import { Ubuntu } from 'next/font/google';

const baseFont = Ubuntu({
  weight: '400',
  style: 'normal',
  subsets: ['latin', 'latin-ext'],
});

export const metadata: Metadata = {
  title: 'Multi step form',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={baseFont.className}>{children}</body>
    </html>
  );
}
